FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install

WORKDIR /app/packages/db
RUN pnpm install
RUN pnpm prisma generate

WORKDIR /app/apps/server
RUN pnpm install
RUN pnpm run build

EXPOSE 8080
CMD ["pnpm", "start"]
