name: Deployment of backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@13.201.102.194 << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
            docker stop user_backend || true
            docker rm user_backend || true
            docker run --name user_backend -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          EOF
